### ISSUE TITLE
Feature Request - Frequency grid in Sonogram View

### ISSUE THREAD

**Issue by crshrprt** [rty65tt/AudioAnalyzer#1]
Thank you for this interesting plugin.

It would be useful to have a frequency grid also in the sonogram view too, without a grid is difficult to understand which frequencies are being played.

**Comment by rty65tt** [comment]
Hi. I don't recommend using my plugin right now. He has problems, he sometimes crushing. Need many remake.  
The frequency under the cursor is displayed if you click on the ">" button (at the top, the last one on the right). So far, then maybe I'll redo it.

**Comment by crshrprt** [comment]
Your plugin worked fine in my tests, much better than some others actually. :)

I saw the recent addition of the frequency indicator under the mouse cursor, very helpful. 
However, having a grid in the sonogram would be useful too, as is already showed in the spectrogram.

Hope you will consider it in the future, thank you.

**Comment by rty65tt** [comment]
> Your plugin worked fine in my tests, much better than some others actually. :)

what the DAW you use?

**Comment by crshrprt** [comment]
BespokeSynth and Ardour

**Comment by rty65tt** [comment]
> BespokeSynth and Ardour

Linux?  

I update, add frequency scale line

**Comment by crshrprt** [comment]
Yes
